services:
  PLejeune\StreamBundle\Service\StreamService:
    public: true
    class: PLejeune\StreamBundle\Service\StreamService
    arguments: ["@service_container"]
  plejeune.stream:
    public: true
    alias: PLejeune\StreamBundle\Service\StreamService

  plejeune.stream.twig:
    public: true
    class: PLejeune\StreamBundle\Extension\StreamExtension
    arguments: ["@service_container"]
    tags:
      - { name: twig.extension }

  plejeune.stream.command.retrieve:
    public: true
    class: PLejeune\StreamBundle\Command\RetrieveCommand
    tags:
      - { name: console.command }
  plejeune.stream.command.refresh:
    public: true
    class: PLejeune\StreamBundle\Command\RefreshCommand
    tags:
      - { name: console.command }