<?php

namespace Darkanakin41\StreamBundle\Repository;

use Darkanakin41\StreamBundle\Entity\Stream;
use Darkanakin41\StreamBundle\Nomenclature\StatusNomenclature;

/**
 * StreamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StreamRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * Get a random stream
     * @return null|Stream
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findRandom() {
        $fields = ["viewers", "updated", "language", "platform", "viewers", "id"];
        $orders = ["ASC", "DESC"];

        $qb = $this->createQueryBuilder("s");
        $qb->leftJoin("s.category", "sc");
        $qb->where("s.status = :status");
        $qb->andWhere("sc.displayed = 1");

        $qb->orderBy(sprintf("s.%s", $fields[array_rand($fields)]), $orders[array_rand($orders)]);

        $qb->setParameter("status", StatusNomenclature::ONLINE);
        $qb->setMaxResults(1);

        return $qb->getQuery()->getOneOrNullResult();
    }

}
