<?php

namespace PLejeune\StreamBundle\Repository;

use PLejeune\StreamBundle\Entity\StreamCategory;

/**
 * StreamCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StreamCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find the stream category
     *
     * @param $provider
     * @param $plateformKey
     *
     * @return StreamCategory|null
     */
    public function findByKey($provider, $plateformKey){
        $qb = $this->createQueryBuilder("c");

        $categories = $qb->getQuery()->getResult();

        $result = null;
        foreach($categories as $category){
            foreach($category->getPlatformKeys() as $key => $value) {
                if ($value != $plateformKey) continue;
                if (stripos($key, sprintf("%s_", $provider)) !== 0) continue;
                $result = $category;
                break;
            }
        }
        return $result;
    }
}
