FROM gfiorleans.azurecr.io/inetum-docker/php-7.3:latest
LABEL maintainer="Pierre LEJEUNE <darkanakin41@gmail.com>"

RUN apk add --no-cache --virtual .build-deps $PHPIZE_DEPS

RUN yes | pecl install xdebug && docker-php-ext-enable xdebug

RUN docker-php-ext-install mbstring

ENV COMPOSER_HOME /composer
ENV PATH /composer/vendor/bin:$PATH
ENV COMPOSER_ALLOW_SUPERUSER 1

COPY --from=composer /usr/bin/composer /usr/bin/composer

RUN mkdir -p "$COMPOSER_HOME/cache" \
&& mkdir -p "$COMPOSER_HOME/vendor" \
&& chown -R www-data:www-data $COMPOSER_HOME \
&& chown -R www-data:www-data /var/www

RUN apk del -f .build-deps

VOLUME /composer/cache
